version: '3.5'
services:
  frontend:
    stdin_open: true
    image: erlingdevold/td:latest
    container_name: td_frontend_prod
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./caddy/data:/data
        - ./caddy/config:/config