version: '3.5'
services:
  tdctl_frontend:
    container_name: frontend_dev
    build:
      context: ..
      dockerfile: .docker/dockerfile.development
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - ../:/app
