FROM node:14 AS build-stage

WORKDIR /app

# copy frontend folder to /app
COPY . /app

#install dependencies
RUN yarn install

#build production app
RUN yarn run build

FROM nginx:alpine

COPY --from=build-stage /app/build /usr/share/nginx/html
COPY --from=build-stage /app/.config/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
