FROM node:16 AS build-stage

WORKDIR /app

COPY package.json /app/package.json

COPY src/ /app/src
COPY public/ /app/public
COPY environments/.env.production /app/environments/.env.production
COPY yarn.lock /app/yarn.lock
COPY tsconfig.json /app/tsconfig.json

#install dependencies
RUN yarn install

#build production app
RUN yarn run build

FROM caddy:alpine

COPY --from=build-stage /app/build /srv
COPY .config/Caddyfile /etc/caddy/Caddyfile

EXPOSE 80
EXPOSE 443
EXPOSE 2019
