name: Add new issue to project backlog

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    name: Add issue to project backlog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          # 2 -> master backlog for frontend
          # project automatically sets new items to "Issue under review" column
          project-url: https://github.com/orgs/td-org-uit-no/projects/2
          github-token: ${{ secrets.ISSUE_TO_PROJECT_PAT }}
