name: Frontend-build and push to production
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/dockerfile
          tags: ghcr.io/td-org-uit-no/tdctl-frontend/frontend:latest
