name: Check if code is formatted with Prettier and no warnings from eslint

on:
  push:
    branches: ['master']
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'README.md'
      - 'dev_utils.sh'
  pull_request:
    branches: ['master']
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - 'README.md'
      - 'dev_utils.sh'

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/cache@v4
        name: Configure npm caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run prettier and eslint
        run: |
          yarn install
          yarn run prettier --check './src'
          yarn run eslint -c .config/.eslintrc.json --max-warnings=0 './src'
